{
 "title": "Model Performance Dashboard",
 "description": "Dashboard",
 "time": { "from": "now-55m", "to": "now" },
 "panels": [
  {
   "title": "Feedback Received",
   "type": "timeseries",
   "description": "The total amount of feedback received from users.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "feedback_received_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "URL Length Histogram",
   "type": "histogram",
   "description": "The length of the URL that is checked for phishing. This can be used to detect a distribution shift in the data.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(url_length_bucket) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Time Gauge",
   "type": "gauge",
   "description": "The time taken by the model to run inference for a URL.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(prediction_time_count) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model performance",
   "type": "timeseries",
   "description": "The accuracy of the model determined from the feedback.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "model_performance", "legendFormat": "__auto" }
   ]
  }
 ]
}